#!/usr/bin/env python3
"""
Generates Shared/GeneratedBufoIndex.swift from bufo-data.json + Bufos/ directory.

Run at build time to eliminate runtime file scanning and JSON parsing.
"""

import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
BUFOS_DIR = PROJECT_ROOT / "Bufos"
DATA_JSON = PROJECT_ROOT / "bufo-data.json"
OUTPUT = PROJECT_ROOT / "Shared" / "GeneratedBufoIndex.swift"


def main() -> int:
    if not DATA_JSON.exists():
        print(f"error: {DATA_JSON} not found", file=sys.stderr)
        return 1
    if not BUFOS_DIR.is_dir():
        print(f"error: {BUFOS_DIR} not found", file=sys.stderr)
        return 1

    with DATA_JSON.open() as f:
        data = json.load(f)

    metadata_by_id = {}
    for entry in data.get("bufos", []):
        bufo_id = entry.get("id")
        if not bufo_id:
            continue
        metadata_by_id[bufo_id] = {
            "tags": entry.get("tags", []) or [],
            "fileType": entry.get("fileType"),
        }

    # Discover actual files on disk so the index reflects what's in the bundle.
    # Prefer animated (gif) over static (png) when both exist.
    valid_exts = {"png", "gif", "jpg", "jpeg"}
    by_id = {}
    for path in sorted(BUFOS_DIR.iterdir()):
        if path.name.startswith("."):
            continue
        ext = path.suffix.lstrip(".").lower()
        if ext not in valid_exts:
            continue
        bufo_id = path.stem
        existing = by_id.get(bufo_id)
        if existing and existing["ext"] == "gif":
            continue  # already prefer animated
        if existing and ext != "gif":
            continue  # keep existing non-gif
        meta = metadata_by_id.get(bufo_id, {"tags": []})
        by_id[bufo_id] = {
            "ext": ext,
            "tags": meta.get("tags", []),
        }

    sorted_ids = sorted(by_id.keys())
    all_tags = sorted({tag for entry in by_id.values() for tag in entry["tags"]})

    lines = [
        "// AUTO-GENERATED by Scripts/generate-bufo-index.py — DO NOT EDIT",
        "import Foundation",
        "",
        "/// Compiled-in bufo metadata. Eliminates runtime file scanning and JSON parsing.",
        "enum GeneratedBufoIndex {",
        f"    /// All bufo IDs sorted alphabetically (count: {len(sorted_ids)}).",
        "    static let entries: [(id: String, ext: String, tags: [String])] = [",
    ]
    for bufo_id in sorted_ids:
        entry = by_id[bufo_id]
        tags_swift = ", ".join(f'"{t}"' for t in entry["tags"])
        lines.append(
            f'        ("{bufo_id}", "{entry["ext"]}", [{tags_swift}]),'
        )
    lines.append("    ]")
    lines.append("")
    lines.append(f"    /// All unique tags sorted alphabetically (count: {len(all_tags)}).")
    lines.append("    static let allTags: [String] = [")
    for tag in all_tags:
        lines.append(f'        "{tag}",')
    lines.append("    ]")
    lines.append("}")
    lines.append("")

    output_text = "\n".join(lines)

    # Only write if changed (avoids triggering needless rebuilds)
    if OUTPUT.exists():
        existing_text = OUTPUT.read_text()
        if existing_text == output_text:
            print(f"GeneratedBufoIndex.swift up to date ({len(sorted_ids)} bufos)")
            return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output_text)
    print(f"Wrote {OUTPUT} ({len(sorted_ids)} bufos, {len(all_tags)} tags)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
